# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  create-md-file:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        
        pip install -r requirements.txt
    - name: Run main.py
      run: |
        python main.py
      env:
        API_KEY_YT: ${{ secrets.YT_API_KEY }}

    - name: Commit md file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add yt_videos.md
        git diff --exit-code
        if [ $? -ne 0 ]; than
          git commit -m 'Add md file generated by Python script'
          git push
        else
          echo "Nothing to commit"
        fi
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
